location         = "West Europe"
rg_name          = "az-euw-syn-dev-pract-dbt-rg01"
aci_name         = "dbt-job-dev"
cpu              = "0.5"
memory           = "1"
dbt_target       = "dev"
keyvault_url     = "https://secrets-aci-dev.vault.azure.net"
cert_secret_name = "snowflake-certificate-dev"

tags = {
  provider                = "az"
  region                  = "euw"
  enterprise              = "syn"
  account                 = "dev"
  system                  = "pract"
  environment             = "dev"
  cmdb_name               = "dbt-pipeline-dev"
  security_exposure_level = "MZ"
  status                  = "active"
  on_service              = "yes"
  managed_by              = "terraform"
  deployment_type         = "trunk-based"
}
